name: unifedi_api
version: 1.0.8

description: Unified API wrapper for Fediverse servers (Pleroma, Mastodon, etc)
homepage: https://github.com/Big-Fig/Fediverse.app
repository: https://github.com/Big-Fig/Fediverse.app

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  fediverse_api:
    git:
      url: https://github.com/Big-Fig/Fediverse.app.git
      path: packages/fediverse_api

  mastodon_api:
    git:
      url: https://github.com/Big-Fig/Fediverse.app.git
      path: packages/mastodon_api

  pleroma_api:
    git:
      url: https://github.com/Big-Fig/Fediverse.app.git
      path: packages/pleroma_api

  # Disposable logic
  easy_dispose: ^1.1.0
  easy_dispose_rxdart: ^1.1.0
  http: ^0.13.3
  logging: ^1.0.2
  path: ^1.8.0
  hive:
    git:
      url: https://github.com/xal/hive
      ref: xal/nested_type_registry2
      path: hive
  json_annotation: ^4.1.0
  freezed_annotation: ^0.14.3
  collection: ^1.15.0

dev_dependencies:
  test: ^1.17.9
  mockito: ^5.0.16
  # additional linters
  dart_code_metrics: ^4.3.3
  lints: 1.0.1
  hive_generator:
    git:
      url: https://github.com/xal/hive
      ref: xal/nested_type_registry2
      path: hive_generator
  json_serializable: ^5.0.2
  freezed: ^0.14.5
  build_runner: ^2.1.2

  # helper to specify all rules in one line
  all_lint_rules_community: ^0.0.4

  fediverse_api_test_utils:
#    path: ../fediverse_api_test_utils
    git:
      url: https://github.com/Big-Fig/Fediverse.app.git

      path: packages/fediverse_api_test_utils