include: package:lints/recommended.yaml

analyzer:
  plugins:
    - dart_code_metrics

linter:
  rules:
    - prefer_relative_imports
    - avoid_dynamic_calls
    - avoid_print
    - avoid_returning_null_for_future
    - avoid_slow_async_io
    - avoid_type_to_string
    - avoid_web_libraries_in_flutter
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - diagnostic_describe_all_properties
    - invariant_booleans
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_logic_in_create_state
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_statements
    - unsafe_html
    - use_key_in_widget_constructors
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - avoid_annotating_with_dynamic
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_classes_with_only_static_members
    - avoid_double_and_int_checks
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_escaping_inner_quotes
    - avoid_field_initializers_in_const_classes
    - avoid_implementing_value_types
    - avoid_js_rounded_ints
    - avoid_positional_boolean_parameters
    - avoid_private_typedef_functions
    - avoid_redundant_argument_values
    - avoid_returning_null
    - avoid_returning_this
    - avoid_setters_without_getters
    - avoid_types_on_closure_parameters
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cascade_invocations
    - cast_nullable_to_non_nullable
    - directives_ordering
    - do_not_use_environment
    - flutter_style_todos
    - join_return_with_assignment
    - leading_newlines_in_multiline_strings
    - lines_longer_than_80_chars
    - missing_whitespace_between_adjacent_strings
    - no_runtimeType_toString
    - omit_local_variable_types
    - one_member_abstracts
    - only_throw_errors
    - package_api_docs
    - parameter_assignments
    - prefer_asserts_in_initializer_lists
    - prefer_asserts_with_message
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - prefer_expression_function_bodies
    #    - prefer_final_in_for_each
    #    - prefer_final_locals
    - prefer_foreach
    - prefer_if_elements_to_conditional_expressions
    - prefer_int_literals
    - prefer_interpolation_to_compose_strings
    - prefer_mixin
    - prefer_single_quotes
    #    - public_member_api_docs
    - type_annotate_public_apis
    - unawaited_futures
    - unnecessary_null_aware_assignments
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - use_full_hex_values_for_flutter_colors
    - use_is_even_rather_than_modulo
    - use_string_buffers
    - use_to_and_as_if_applicable
    - use_raw_strings
    - sort_pub_dependencies

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    lines-of-code: 100
    source-lines-of-code: 50
    maximum-nesting: 5
    weight-of-class: 0.33
    number-of-arguments: 6
    number-of-parameters: 6
    number-of-methods: 4
  metrics-exclude:
    - test/**
  rules:
    - avoid-late-keyword
    - avoid-non-null-assertion
    - avoid-unused-parameters
    - binary-expression-operand-order
    - double-literal-format
    - member-ordering
    - member-ordering-extended
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - no-equal-arguments
    - no-equal-then-else
    - no-magic-number
    - no-object-declaration
    - prefer-conditional-expressions
    - prefer-trailing-comma