# Copyright (c) 2019, the Dart project authors.  Please see the AUTHORS file
# for details. All rights reserved. Use of this source code is governed by a
# BSD-style license that can be found in the LICENSE file.
#
# Google internally enforced rules. See README.md for more information,
# including a list of lints that are intentionally _not_ enforced.
include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    - test/resources/**
    - test/**/examples/**
    - lib/generated/**
    - lib/**.g.dart
    - test/**.mocks.dart
  plugins:
    - dart_code_metrics

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    lines-of-code: 100
    lines-of-executable-code: 50
    maximum-nesting: 5
    number-of-arguments: 5
    number-of-methods: 4
    weight-of-class: 0.33
  metrics-exclude:
    - test/**
  rules:
    - prefer-trailing-comma
    - avoid-unused-parameters
    - binary-expression-operand-order
    - double-literal-format
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - no-equal-then-else
    - no-equal-arguments
    - no-object-declaration
    - no-magic-number
#    - member-ordering

linter:
  rules:
    prefer_single_quotes: false
    omit_local_variable_types: false