name: fedi
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.3+25

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  firebase_core: ^0.4.0+9
  firebase_messaging: ^6.0.9
  firebase_analytics: ^5.0.2
  cupertino_icons: ^0.1.2
  webview_flutter: ^0.3.9
  http: ^0.12.0
  uni_links: ^0.2.0
  url_launcher: ^5.2.7
  hive: ^0.4.1
  hive_generator: ^0.4.0+1
  pull_to_refresh: ^1.5.4
  flutter_html: ^0.10.4
  flutter_staggered_grid_view: ^0.3.0
  video_player: ^0.10.4+1
  path_provider: ^1.4.5
  photo_manager:
   git:
    url: https://github.com/CaiJingLong/flutter_photo_manager.git
    ref: f3331b6584609984574bd11cd93fc91ae485de72
  camera: ^0.5.7
  carousel_pro: ^1.0.0
  scoped_model: any
  percent_indicator: "^2.1.1"
  mime_type: ^0.2.4
  # flutter_webrtc: any
  material_segmented_control: ^2.0.3
  flutter_alert: ^0.4.0
  firebase_crashlytics: any
  timeago: ^2.0.26
  chewie: ^0.9.8+1
  photo_view: ^0.9.0
  indexed_list_view: ^1.0.8
  flutter_widgets: ^0.1.7+1
  image_cropper: ^1.1.1
  cached_network_image: ^2.0.0
  rxdart: ^0.23.1
  auto_size_text: ^2.1.0
  badges: ^1.1.0
  vibration: ^1.2.2
  fluttertoast: ^3.1.3
  
  # localization via .json files
  #easy_localization: ^1.3.1
  # Actually it is 1.3.1 with minor fix from me (Yevhenii Zapletin)
  easy_localization:
    git:
      url: https://github.com/xal/easy_localization.git
      ref: xal/fixQuickSwitchLocaleException
  
  # annotations to generate json from & to methods
  json_annotation: ^3.0.1

  # advanced logging
  logging: ^0.11.4
  # dependency injection framework
  provider: ^4.0.3

  # fancy permission handler
  permission_handler: ^4.2.0+hotfix.3

  # better tab indicator
  md2_tab_indicator: ^1.0.2

  # native kotlin/swift image convert & compress
  flutter_image_compress: ^0.6.5+1

  # WebSockets API mobile implementation
  web_socket_channel: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # build tools runner
  # usage example
  # flutter pub run build_runner build --delete-conflicting-outputs
  build_runner: ^1.7.3
  # build tool to generate json from & to methods
  json_serializable: ^3.2.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/terms/terms.rtf
    - assets/images/theme/logo.png
    - assets/images/double_ring_loading_io.gif
    - assets/langs/en-US.json
    - assets/images/comment-icon.png
    - assets/images/comment.png
    - assets/images/favorites.png
    - assets/images/repost.png
    - assets/images/share.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
