name: fedi
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.45+245

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # enhanced reorderable list
  flutter_reorderable_list: ^0.1.5

  # firebase auth
  firebase_core: ^0.5.0
  # push notifications FCM
  firebase_messaging: ^7.0.0
  # analytics events
  firebase_analytics: ^6.0.0
  # handle crashes and non-fatal errors
  firebase_crashlytics: 0.2.1

  # handle init urls. Used for login/register and navigation from notification
  uni_links: ^0.4.0
  # launch browser to view links
  url_launcher: ^5.6.0
  # object serialization
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1

  #flutter_html: ^1.0.2
  # actually it is ^1.0.2 with additional text style features
  flutter_html:
    git:
      url: https://github.com/xal/flutter_html.git
      ref: 182bc3e3b9bb6704abbd1576be4dca2947616f51

  #flutter_duration_picker: ^1.0.4
  # actually it is ^1.0.4 with bug fixes & style improvements
  flutter_duration_picker:
    git:
      url: https://github.com/xal/flutter_duration_picker
      ref: xal/minute_fixes

  # media grid
  flutter_staggered_grid_view: ^0.3.2
  # retrieve storage path to save files
  path_provider: ^1.6.14
  # fetch gallery albums and items
  photo_manager: ^0.5.8
  # detect file mime type for share
  mime_type: ^0.3.2
  # datetime formatter for statuses & chat messages
  timeago: ^2.0.27
  # better image viewer with gestures support
  photo_view: ^0.10.2
  # positioned list view
  scrollable_positioned_list: ^0.1.8
  # edit images during account editing
  image_cropper: ^1.3.1
  # cache images locally
  cached_network_image: ^2.5.0
  # cache manager for cached_network_image. Use to set up cache settings
  flutter_cache_manager: ^2.1.0
  # reactive programming
  rxdart: ^0.24.1
  # text size to fit constraints
  auto_size_text: ^2.1.0

  # default media picker
  image_picker: ^0.6.7+4

  # better lint, should be in main dependencies to ignore async/await unnecessary warnings
  pedantic: ^1.8.0+1

  # customizable datetime picker
  flutter_datetime_picker: ^1.4.0

  # annotations to generate json from & to methods
  json_annotation: ^3.0.1

  # advanced logging
  logging: ^0.11.4

  # dependency injection framework
  provider: ^4.3.2+2

  # fancy permission handler
  permission_handler: ^5.0.1+1

  # better tab indicator
  md2_tab_indicator: ^1.0.2

  # native kotlin/swift image convert & compress
  flutter_image_compress: ^0.6.5+1

  # commandline script to pull database from emulator
  # adb exec-out run-as com.fediverse.app cat ./databases/jffdev@fedi.app.sqlite > database.sqlite
  # sqlite orm
  moor: ^3.4.0

  # sqlite3_flutter_libs required for moor ffi
  sqlite3_flutter_libs: ^0.2.0

  # database inspector for debugging. Use with Moor Inspector Intellij Idea Plugin
  moor_inspector: ^0.1.3

  # check internet connection state
  connectivity: ^0.4.9+2

  # WebSockets API mobile implementation
  web_socket_channel: ^1.1.0

  # Provides internationalization and localization facilities
  intl: ^0.16.1

  # save photo and video to gallery
  gallery_saver: ^2.0.3

  # share actions via native API
  esys_flutter_share: ^1.0.2

  # detect mime type be extension
  mime: ^0.9.7

  # parse html to extract raw text from status content
  html: ^0.14.0+3

  # fetch package info during runtime
  package_info: ^0.4.3

  # better scroll controller for nested scroll
  nested_scroll_controller: ^0.2.1

  # media attachments carousel
  carousel_slider: ^2.2.1

  # video/audio players
  video_player: '>=0.10.11+2 <2.0.0'

  # pull to refresh and pull to load more
  pull_to_refresh: ^1.6.2

  # custom scroll view which fix bugs related to inner scrollables sync
  extended_nested_scroll_view: ^1.0.1

  # error overlay
  overlay_support: ^1.0.5

  # file picker for media attachment
  file_picker: ^2.0.0

  # unenscape account not field
  html_unescape: ^1.0.2

  # shared preferences support. temporary required by custom emoji picker Todo: refactor and remove
  shared_preferences: ^0.5.10

  # extended text fields with highlight mentions support
  extended_text_field: ^5.0.0

  # detect keyboard visibility
  flutter_keyboard_visibility: ^3.2.2

  # list view item slide actions
  flutter_slidable: ^0.5.7

  # disable wakelock for video player
  wakelock: ^0.1.4+2

  # ask for review inside app
  in_app_review: ^1.0.4

  # better dateTime manipulation (especially for add duration to dateTime)
  jiffy: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # easy mock for tests
  mockito: ^4.1.1
  # build tools runner
  # usage example
  # flutter pub run build_runner build --delete-conflicting-outputs
  build_runner: ^1.10.4
  # build tool to generate json from & to methods
  json_serializable: ^3.4.1
  # sql orm generator
  moor_generator: ^3.4.0

  # object serialization generator
  hive_generator: ^0.8.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: FediIcons
      fonts:
        - asset: assets/fonts/FediIcons.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/terms/terms.rtf
    - assets/images/theme/logo.png
    - assets/images/default_timeline_header.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
