name: fedi
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1.2+256

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # enhanced reorderable list
  flutter_reorderable_list: ^1.0.0

  # firebase auth
  firebase_core: ^1.1.0
  # push notifications FCM
  firebase_messaging: ^9.1.3

  # handle crashes and non-fatal errors
  firebase_crashlytics: ^2.0.2

  # handle init urls. Used for login/register and navigation from notification
  # actually uni_links fork with null-safety
  uni_links: ^0.5.1

  # launch browser to view links
  url_launcher: ^6.0.3
  # object serialization
  hive: ^2.0.4
  hive_flutter: ^1.0.0

  #  flutter_html: ^2.0.0-nullsafety.0
  #   actually it is ^2.0.0-nullsafety.0 with additional text style features and libs update
  flutter_html:
    git:
      url: https://github.com/xal/flutter_html.git
      ref: f7559889775e8f773f2104958bf8178b7b4380f0

  # minutes/hours picker
  # duration_picker: ^1.0.1
  # it is 1.0.1 with minute fixes and widget layout changes
  duration_picker:
    git:
      url: https://github.com/xal/duration_picker.git
      ref: ea2decc7d3f6cf2ebb7ff01570268045da71f647

  # media grid
  flutter_staggered_grid_view: ^0.4.0
  # retrieve storage path to save files
  path_provider: ^2.0.1
  # fetch gallery albums and items
  photo_manager: ^1.1.4
  # detect file mime type for share
  mime_type: ^1.0.0
  # datetime formatter for statuses & chat messages
  timeago: ^3.0.2
  # better image viewer with gestures support
  photo_view: ^0.11.1
  # positioned list view
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  # edit images during account editing
  image_cropper: ^1.4.0
  # cache images locally
  cached_network_image: ^3.0.0
  # cache manager for cached_network_image. Use to set up cache settings
  flutter_cache_manager: ^3.0.1
  # reactive programming
  rxdart: ^0.26.0
  # text size to fit constraints
  auto_size_text: ^3.0.0-nullsafety.0

  # default media picker
  image_picker: ^0.7.4

  # better lint, should be in main dependencies to ignore async/await unnecessary warnings
  pedantic: ^1.11.0

  # customizable datetime picker
  flutter_datetime_picker: ^1.5.1

  # annotations to generate json from & to methods
  json_annotation: ^4.0.1

  # advanced logging
  logging: ^1.0.1

  # dependency injection framework
  provider: ^5.0.0

  # fancy permission handler
  permission_handler: ^7.1.0

  # native kotlin/swift image convert & compress
  flutter_image_compress: ^1.0.0

  # commandline script to pull database from emulator
  # adb exec-out run-as com.fediverse.app cat ./databases/jffdev@fedi.app.sqlite > database.sqlite
  # sqlite orm
  moor: ^4.2.1

  # sqlite3_flutter_libs required for moor ffi
  sqlite3_flutter_libs: ^0.4.1

  # database inspector for debugging. Use with Moor Inspector Intellij Idea Plugin
  moor_inspector: ^0.2.0

  # check internet connection state
  connectivity: ^3.0.2

  # WebSockets API mobile implementation
  web_socket_channel: ^2.0.0

  # save photo and video to gallery
  gallery_saver: ^2.1.0

  # share actions via native API
  share: ^2.0.1

  # detect mime type be extension
  mime: ^1.0.0

  # parse html to extract raw text from status content
  html: ^0.15.0

  # fetch package info during runtime
  package_info: ^2.0.0

  # better scroll controller for nested scroll
  nested_scroll_controller: ^1.0.0

  # media attachments carousel
  carousel_slider: ^4.0.0-nullsafety.0

  # video/audio players
  video_player: ^2.1.1

  # pull to refresh and pull to load more
  # null-safety fork from original
  #  pull_to_refresh: ^1.6.4
  pull_to_refresh:
    git:
      url: https://github.com/fzyzcjy/flutter_pulltorefresh.git
      ref: 0bb4f70dd7540ffe032bbc2a6994df388b4f1c39

  # custom scroll view which fix bugs related to inner scrollables sync
  extended_nested_scroll_view: ^3.0.0

  # error overlay
  overlay_support: ^1.2.1

  # file picker for media attachment
  file_picker: ^3.0.1

  # unenscape account not field
  html_unescape: ^2.0.0

  # shared preferences support. temporary required by custom emoji picker Todo: refactor and remove
  shared_preferences: ^2.0.5

  # extended text fields with highlight mentions support
  extended_text_field: ^7.0.1

  # detect keyboard visibility
  flutter_keyboard_visibility: ^5.0.1

  # list view item slide actions
  flutter_slidable: ^0.6.0

  # disable wakelock for video player
  wakelock: ^0.4.0

  # ask for review inside app
  in_app_review: ^2.0.2

  # better dateTime manipulation (especially for add duration to dateTime)
  jiffy: ^4.1.0

  # collections extensions
  collection: ^1.15.0

  # customizable switch widget
  flutter_switch: ^0.3.1

dependency_overrides:
  # dev_dependencies conflict:
  # hive_generator 1.0.0 which is null-safe uses web_socket_channel: ^2.0.0
  # build_runner: ^1.11.5 which is not null-safe uses web_socket_channel: ^1.0.0
  web_socket_channel: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # easy mock for tests
  mockito: ^5.0.7
  # build tools runner
  # usage example
  # flutter pub run build_runner build --delete-conflicting-outputs
#  build_runner: ^1.11.5
  build_runner: ^2.0.2
  # build tool to generate json from & to methods
  json_serializable: ^4.1.1
  # sql orm generator
  moor_generator: ^4.2.2

  # object serialization generator
  hive_generator: ^1.1.0

  # additional linter
  dart_code_metrics: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: FediIcons
      fonts:
        - asset: assets/fonts/FediIcons.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/terms/terms.rtf
    - assets/images/theme/logo.png
    - assets/images/default_timeline_header.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true