// Mocks generated by Mockito 5.0.5 from annotations
// in fedi/test/app/account/account_bloc_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i9;

import 'package:fedi/connection/connection_service.dart' as _i5;
import 'package:fedi/disposable/disposable.dart' as _i15;
import 'package:fedi/pleroma/api/account/auth/pleroma_api_auth_account_service_impl.dart'
    as _i8;
import 'package:fedi/pleroma/api/account/pleroma_api_account_model.dart' as _i4;
import 'package:fedi/pleroma/api/list/pleroma_api_list_model.dart' as _i11;
import 'package:fedi/pleroma/api/pagination/pleroma_api_pagination_model.dart'
    as _i12;
import 'package:fedi/pleroma/api/pleroma_api_api_service.dart' as _i10;
import 'package:fedi/pleroma/api/rest/auth/pleroma_api_auth_rest_service.dart'
    as _i2;
import 'package:fedi/pleroma/api/rest/pleroma_api_rest_service.dart' as _i3;
import 'package:fedi/pleroma/api/status/pleroma_api_status_model.dart' as _i14;
import 'package:fedi/pleroma/api/web_sockets/pleroma_api_web_sockets_model.dart'
    as _i21;
import 'package:fedi/pleroma/api/web_sockets/pleroma_api_web_sockets_service_impl.dart'
    as _i20;
import 'package:fedi/web_sockets/channel/web_sockets_channel.dart' as _i7;
import 'package:fedi/web_sockets/web_sockets_model.dart' as _i6;
import 'package:flutter/src/widgets/editable_text.dart' as _i16;
import 'package:flutter/src/widgets/focus_manager.dart' as _i18;
import 'package:flutter/src/widgets/scroll_controller.dart' as _i17;
import 'package:http/src/response.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rxdart/src/subjects/subject.dart' as _i19;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeIPleromaAuthRestService extends _i1.Fake
    implements _i2.IPleromaAuthRestService {}

class _FakeIPleromaRestService extends _i1.Fake
    implements _i3.IPleromaRestService {}

class _FakeIPleromaAccountRelationship extends _i1.Fake
    implements _i4.IPleromaAccountRelationship {}

class _FakeIPleromaAccount extends _i1.Fake implements _i4.IPleromaAccount {}

class _FakeUri extends _i1.Fake implements Uri {}

class _FakeIConnectionService extends _i1.Fake
    implements _i5.IConnectionService {}

class _FakeIWebSocketsChannel<T extends _i6.WebSocketsEvent> extends _i1.Fake
    implements _i7.IWebSocketsChannel<T> {}

class _FakeWebSocketsEvent extends _i1.Fake implements _i6.WebSocketsEvent {}

/// A class which mocks [PleromaAuthAccountService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPleromaAuthAccountService extends _i1.Mock
    implements _i8.PleromaAuthAccountService {
  MockPleromaAuthAccountService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get accountReportRelativeUrlPath =>
      (super.noSuchMethod(Invocation.getter(#accountReportRelativeUrlPath),
          returnValue: '') as String);
  @override
  _i2.IPleromaAuthRestService get authRestService =>
      (super.noSuchMethod(Invocation.getter(#authRestService),
              returnValue: _FakeIPleromaAuthRestService())
          as _i2.IPleromaAuthRestService);
  @override
  bool get isPleroma =>
      (super.noSuchMethod(Invocation.getter(#isPleroma), returnValue: false)
          as bool);
  @override
  _i9.Stream<_i10.PleromaApiState> get pleromaApiStateStream =>
      (super.noSuchMethod(Invocation.getter(#pleromaApiStateStream),
              returnValue: Stream<_i10.PleromaApiState>.empty())
          as _i9.Stream<_i10.PleromaApiState>);
  @override
  _i10.PleromaApiState get pleromaApiState =>
      (super.noSuchMethod(Invocation.getter(#pleromaApiState),
          returnValue: _i10.PleromaApiState.validAuth) as _i10.PleromaApiState);
  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);
  @override
  _i9.Stream<bool> get isConnectedStream =>
      (super.noSuchMethod(Invocation.getter(#isConnectedStream),
          returnValue: Stream<bool>.empty()) as _i9.Stream<bool>);
  @override
  bool get isMastodon =>
      (super.noSuchMethod(Invocation.getter(#isMastodon), returnValue: false)
          as bool);
  @override
  String get accountRelativeUrlPath =>
      (super.noSuchMethod(Invocation.getter(#accountRelativeUrlPath),
          returnValue: '') as String);
  @override
  String get pleromaAccountRelativeUrlPath =>
      (super.noSuchMethod(Invocation.getter(#pleromaAccountRelativeUrlPath),
          returnValue: '') as String);
  @override
  _i3.IPleromaRestService get restService =>
      (super.noSuchMethod(Invocation.getter(#restService),
          returnValue: _FakeIPleromaRestService()) as _i3.IPleromaRestService);
  @override
  bool get isDisposed =>
      (super.noSuchMethod(Invocation.getter(#isDisposed), returnValue: false)
          as bool);
  @override
  set isDisposed(bool? _isDisposed) =>
      super.noSuchMethod(Invocation.setter(#isDisposed, _isDisposed),
          returnValueForMissingStub: null);
  @override
  _i9.Future<List<_i4.IPleromaAccountRelationship>> getRelationshipWithAccounts(
          {List<String>? remoteAccountIds}) =>
      (super.noSuchMethod(
              Invocation.method(#getRelationshipWithAccounts, [],
                  {#remoteAccountIds: remoteAccountIds}),
              returnValue: Future<List<_i4.IPleromaAccountRelationship>>.value(
                  <_i4.IPleromaAccountRelationship>[]))
          as _i9.Future<List<_i4.IPleromaAccountRelationship>>);
  @override
  _i9.Future<_i4.IPleromaAccountRelationship> blockAccount(
          {String? accountRemoteId}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #blockAccount, [], {#accountRemoteId: accountRemoteId}),
              returnValue: Future<_i4.IPleromaAccountRelationship>.value(
                  _FakeIPleromaAccountRelationship()))
          as _i9.Future<_i4.IPleromaAccountRelationship>);
  @override
  _i9.Future<_i4.IPleromaAccountRelationship> followAccount(
          {String? accountRemoteId}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #followAccount, [], {#accountRemoteId: accountRemoteId}),
              returnValue: Future<_i4.IPleromaAccountRelationship>.value(
                  _FakeIPleromaAccountRelationship()))
          as _i9.Future<_i4.IPleromaAccountRelationship>);
  @override
  _i9.Future<_i4.IPleromaAccountRelationship> muteAccount(
          {String? accountRemoteId,
          bool? notifications,
          int? expireDurationInSeconds}) =>
      (super.noSuchMethod(
              Invocation.method(#muteAccount, [], {
                #accountRemoteId: accountRemoteId,
                #notifications: notifications,
                #expireDurationInSeconds: expireDurationInSeconds
              }),
              returnValue: Future<_i4.IPleromaAccountRelationship>.value(
                  _FakeIPleromaAccountRelationship()))
          as _i9.Future<_i4.IPleromaAccountRelationship>);
  @override
  _i9.Future<_i4.IPleromaAccountRelationship> pinAccount(
          {String? accountRemoteId}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #pinAccount, [], {#accountRemoteId: accountRemoteId}),
              returnValue: Future<_i4.IPleromaAccountRelationship>.value(
                  _FakeIPleromaAccountRelationship()))
          as _i9.Future<_i4.IPleromaAccountRelationship>);
  @override
  _i9.Future<_i4.IPleromaAccountRelationship> unBlockAccount(
          {String? accountRemoteId}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #unBlockAccount, [], {#accountRemoteId: accountRemoteId}),
              returnValue: Future<_i4.IPleromaAccountRelationship>.value(
                  _FakeIPleromaAccountRelationship()))
          as _i9.Future<_i4.IPleromaAccountRelationship>);
  @override
  _i9.Future<_i4.IPleromaAccountRelationship> unFollowAccount(
          {String? accountRemoteId}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #unFollowAccount, [], {#accountRemoteId: accountRemoteId}),
              returnValue: Future<_i4.IPleromaAccountRelationship>.value(
                  _FakeIPleromaAccountRelationship()))
          as _i9.Future<_i4.IPleromaAccountRelationship>);
  @override
  _i9.Future<_i4.IPleromaAccountRelationship> unMuteAccount(
          {String? accountRemoteId}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #unMuteAccount, [], {#accountRemoteId: accountRemoteId}),
              returnValue: Future<_i4.IPleromaAccountRelationship>.value(
                  _FakeIPleromaAccountRelationship()))
          as _i9.Future<_i4.IPleromaAccountRelationship>);
  @override
  _i9.Future<_i4.IPleromaAccountRelationship> unPinAccount(
          {String? accountRemoteId}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #unPinAccount, [], {#accountRemoteId: accountRemoteId}),
              returnValue: Future<_i4.IPleromaAccountRelationship>.value(
                  _FakeIPleromaAccountRelationship()))
          as _i9.Future<_i4.IPleromaAccountRelationship>);
  @override
  _i9.Future<List<_i4.IPleromaAccountIdentityProof>> getAccountIdentifyProofs(
          {String? accountRemoteId}) =>
      (super.noSuchMethod(
              Invocation.method(#getAccountIdentifyProofs, [],
                  {#accountRemoteId: accountRemoteId}),
              returnValue: Future<List<_i4.IPleromaAccountIdentityProof>>.value(
                  <_i4.IPleromaAccountIdentityProof>[]))
          as _i9.Future<List<_i4.IPleromaAccountIdentityProof>>);
  @override
  _i9.Future<List<_i11.IPleromaList>> getListsWithAccount(
          {String? accountRemoteId}) =>
      (super.noSuchMethod(
          Invocation.method(
              #getListsWithAccount, [], {#accountRemoteId: accountRemoteId}),
          returnValue: Future<List<_i11.IPleromaList>>.value(
              <_i11.IPleromaList>[])) as _i9.Future<List<_i11.IPleromaList>>);
  @override
  _i9.Future<List<_i4.IPleromaAccount>> search(
          {String? query,
          bool? resolve,
          bool? following,
          _i12.IPleromaPaginationRequest? pagination}) =>
      (super.noSuchMethod(
              Invocation.method(#search, [], {
                #query: query,
                #resolve: resolve,
                #following: following,
                #pagination: pagination
              }),
              returnValue: Future<List<_i4.IPleromaAccount>>.value(
                  <_i4.IPleromaAccount>[]))
          as _i9.Future<List<_i4.IPleromaAccount>>);
  @override
  _i9.Future<bool> reportAccount(
          {_i4.IPleromaAccountReportRequest? reportRequest}) =>
      (super.noSuchMethod(
          Invocation.method(
              #reportAccount, [], {#reportRequest: reportRequest}),
          returnValue: Future<bool>.value(false)) as _i9.Future<bool>);
  @override
  _i9.Future<dynamic> blockDomain({String? domain}) => (super.noSuchMethod(
      Invocation.method(#blockDomain, [], {#domain: domain}),
      returnValue: Future<dynamic>.value(null)) as _i9.Future<dynamic>);
  @override
  _i9.Future<dynamic> unBlockDomain({String? domain}) => (super.noSuchMethod(
      Invocation.method(#unBlockDomain, [], {#domain: domain}),
      returnValue: Future<dynamic>.value(null)) as _i9.Future<dynamic>);
  @override
  _i9.Future<_i4.IPleromaAccountRelationship> subscribeAccount(
          {String? accountRemoteId}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #subscribeAccount, [], {#accountRemoteId: accountRemoteId}),
              returnValue: Future<_i4.IPleromaAccountRelationship>.value(
                  _FakeIPleromaAccountRelationship()))
          as _i9.Future<_i4.IPleromaAccountRelationship>);
  @override
  _i9.Future<_i4.IPleromaAccountRelationship> unSubscribeAccount(
          {String? accountRemoteId}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #unSubscribeAccount, [], {#accountRemoteId: accountRemoteId}),
              returnValue: Future<_i4.IPleromaAccountRelationship>.value(
                  _FakeIPleromaAccountRelationship()))
          as _i9.Future<_i4.IPleromaAccountRelationship>);
  @override
  List<_i4.PleromaAccount> parseAccountListResponse(
          _i13.Response? httpResponse) =>
      (super.noSuchMethod(
          Invocation.method(#parseAccountListResponse, [httpResponse]),
          returnValue: <_i4.PleromaAccount>[]) as List<_i4.PleromaAccount>);
  @override
  List<_i4.IPleromaAccountIdentityProof> parseAccountAccountIdentityProofList(
          _i13.Response? httpResponse) =>
      (super.noSuchMethod(
              Invocation.method(
                  #parseAccountAccountIdentityProofList, [httpResponse]),
              returnValue: <_i4.IPleromaAccountIdentityProof>[])
          as List<_i4.IPleromaAccountIdentityProof>);
  @override
  List<_i11.IPleromaList> parseListList(_i13.Response? httpResponse) =>
      (super.noSuchMethod(Invocation.method(#parseListList, [httpResponse]),
          returnValue: <_i11.IPleromaList>[]) as List<_i11.IPleromaList>);
  @override
  List<_i14.IPleromaStatus> parseStatusListResponse(
          _i13.Response? httpResponse) =>
      (super.noSuchMethod(
          Invocation.method(#parseStatusListResponse, [httpResponse]),
          returnValue: <_i14.IPleromaStatus>[]) as List<_i14.IPleromaStatus>);
  @override
  _i4.IPleromaAccountRelationship parseAccountRelationshipResponse(
          _i13.Response? httpResponse) =>
      (super.noSuchMethod(
          Invocation.method(#parseAccountRelationshipResponse, [httpResponse]),
          returnValue:
              _FakeIPleromaAccountRelationship()) as _i4
          .IPleromaAccountRelationship);
  @override
  List<_i4.IPleromaAccountRelationship> parseAccountRelationshipResponseList(
          _i13.Response? httpResponse) =>
      (super.noSuchMethod(
              Invocation.method(
                  #parseAccountRelationshipResponseList, [httpResponse]),
              returnValue: <_i4.IPleromaAccountRelationship>[])
          as List<_i4.IPleromaAccountRelationship>);
  @override
  _i4.IPleromaAccount parseAccountResponse(_i13.Response? httpResponse) =>
      (super.noSuchMethod(
          Invocation.method(#parseAccountResponse, [httpResponse]),
          returnValue: _FakeIPleromaAccount()) as _i4.IPleromaAccount);
  @override
  _i9.Future<List<_i4.IPleromaAccount>> getAccountFollowings(
          {String? accountRemoteId,
          _i12.IPleromaPaginationRequest? pagination}) =>
      (super.noSuchMethod(
              Invocation.method(#getAccountFollowings, [],
                  {#accountRemoteId: accountRemoteId, #pagination: pagination}),
              returnValue: Future<List<_i4.IPleromaAccount>>.value(
                  <_i4.IPleromaAccount>[]))
          as _i9.Future<List<_i4.IPleromaAccount>>);
  @override
  _i9.Future<_i4.IPleromaAccount> getAccount({String? accountRemoteId}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getAccount, [], {#accountRemoteId: accountRemoteId}),
              returnValue:
                  Future<_i4.IPleromaAccount>.value(_FakeIPleromaAccount()))
          as _i9.Future<_i4.IPleromaAccount>);
  @override
  _i9.Future<List<_i4.PleromaAccount>> getAccountFollowers(
          {String? accountRemoteId,
          _i12.IPleromaPaginationRequest? pagination}) =>
      (super.noSuchMethod(
          Invocation.method(#getAccountFollowers, [],
              {#accountRemoteId: accountRemoteId, #pagination: pagination}),
          returnValue: Future<List<_i4.PleromaAccount>>.value(
              <_i4.PleromaAccount>[])) as _i9.Future<List<_i4.PleromaAccount>>);
  @override
  _i9.Future<List<_i14.IPleromaStatus>> getAccountStatuses(
          {String? accountRemoteId,
          String? tagged,
          bool? pinned,
          bool? excludeReplies,
          bool? excludeReblogs,
          List<String>? excludeVisibilities,
          bool? withMuted,
          bool? onlyWithMedia,
          _i12.IPleromaPaginationRequest? pagination}) =>
      (super.noSuchMethod(
              Invocation.method(#getAccountStatuses, [], {
                #accountRemoteId: accountRemoteId,
                #tagged: tagged,
                #pinned: pinned,
                #excludeReplies: excludeReplies,
                #excludeReblogs: excludeReblogs,
                #excludeVisibilities: excludeVisibilities,
                #withMuted: withMuted,
                #onlyWithMedia: onlyWithMedia,
                #pagination: pagination
              }),
              returnValue: Future<List<_i14.IPleromaStatus>>.value(
                  <_i14.IPleromaStatus>[]))
          as _i9.Future<List<_i14.IPleromaStatus>>);
  @override
  _i9.Future<List<_i14.IPleromaStatus>> getAccountFavouritedStatuses(
          {String? accountRemoteId,
          _i12.IPleromaPaginationRequest? pagination}) =>
      (super.noSuchMethod(
              Invocation.method(#getAccountFavouritedStatuses, [],
                  {#accountRemoteId: accountRemoteId, #pagination: pagination}),
              returnValue: Future<List<_i14.IPleromaStatus>>.value(
                  <_i14.IPleromaStatus>[]))
          as _i9.Future<List<_i14.IPleromaStatus>>);
  @override
  void addDisposable(
          {_i15.IDisposable? disposable,
          _i9.StreamSubscription<dynamic>? streamSubscription,
          _i16.TextEditingController? textEditingController,
          _i17.ScrollController? scrollController,
          _i18.FocusNode? focusNode,
          _i19.Subject<dynamic>? subject,
          _i9.StreamController<dynamic>? streamController,
          _i9.Timer? timer,
          _i9.FutureOr<dynamic>? Function()? custom}) =>
      super.noSuchMethod(
          Invocation.method(#addDisposable, [], {
            #disposable: disposable,
            #streamSubscription: streamSubscription,
            #textEditingController: textEditingController,
            #scrollController: scrollController,
            #focusNode: focusNode,
            #subject: subject,
            #streamController: streamController,
            #timer: timer,
            #custom: custom
          }),
          returnValueForMissingStub: null);
  @override
  _i9.Future<dynamic> dispose() =>
      (super.noSuchMethod(Invocation.method(#dispose, []),
          returnValue: Future<dynamic>.value(null)) as _i9.Future<dynamic>);
}

/// A class which mocks [PleromaWebSocketsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPleromaWebSocketsService extends _i1.Mock
    implements _i20.PleromaWebSocketsService {
  MockPleromaWebSocketsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Uri get baseUri =>
      (super.noSuchMethod(Invocation.getter(#baseUri), returnValue: _FakeUri())
          as Uri);
  @override
  String get accessToken =>
      (super.noSuchMethod(Invocation.getter(#accessToken), returnValue: '')
          as String);
  @override
  _i5.IConnectionService get connectionService =>
      (super.noSuchMethod(Invocation.getter(#connectionService),
          returnValue: _FakeIConnectionService()) as _i5.IConnectionService);
  @override
  bool get isDisposed =>
      (super.noSuchMethod(Invocation.getter(#isDisposed), returnValue: false)
          as bool);
  @override
  set isDisposed(bool? _isDisposed) =>
      super.noSuchMethod(Invocation.setter(#isDisposed, _isDisposed),
          returnValueForMissingStub: null);
  @override
  _i7.IWebSocketsChannel<_i21.PleromaWebSocketsEvent> getOrCreateNewChannel(
          {String? stream, Map<String, String?>? queryArgs}) =>
      (super.noSuchMethod(
              Invocation.method(#getOrCreateNewChannel, [],
                  {#stream: stream, #queryArgs: queryArgs}),
              returnValue:
                  _FakeIWebSocketsChannel<_i21.PleromaWebSocketsEvent>())
          as _i7.IWebSocketsChannel<_i21.PleromaWebSocketsEvent>);
  @override
  String mapHttpToWebSocketsScheme(String? scheme) => (super.noSuchMethod(
      Invocation.method(#mapHttpToWebSocketsScheme, [scheme]),
      returnValue: '') as String);
  @override
  _i7.IWebSocketsChannel<_i21.PleromaWebSocketsEvent> getHashtagChannel(
          {String? hashtag, bool? local}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getHashtagChannel, [], {#hashtag: hashtag, #local: local}),
              returnValue:
                  _FakeIWebSocketsChannel<_i21.PleromaWebSocketsEvent>())
          as _i7.IWebSocketsChannel<_i21.PleromaWebSocketsEvent>);
  @override
  _i7.IWebSocketsChannel<_i21.PleromaWebSocketsEvent> getListChannel(
          {String? listId}) =>
      (super.noSuchMethod(
              Invocation.method(#getListChannel, [], {#listId: listId}),
              returnValue:
                  _FakeIWebSocketsChannel<_i21.PleromaWebSocketsEvent>())
          as _i7.IWebSocketsChannel<_i21.PleromaWebSocketsEvent>);
  @override
  _i7.IWebSocketsChannel<_i21.PleromaWebSocketsEvent> getPublicChannel(
          {bool? onlyLocal,
          bool? onlyRemote,
          bool? onlyMedia,
          String? onlyFromInstance}) =>
      (super.noSuchMethod(
              Invocation.method(#getPublicChannel, [], {
                #onlyLocal: onlyLocal,
                #onlyRemote: onlyRemote,
                #onlyMedia: onlyMedia,
                #onlyFromInstance: onlyFromInstance
              }),
              returnValue:
                  _FakeIWebSocketsChannel<_i21.PleromaWebSocketsEvent>())
          as _i7.IWebSocketsChannel<_i21.PleromaWebSocketsEvent>);
  @override
  _i7.IWebSocketsChannel<_i21.PleromaWebSocketsEvent> getAccountChannel(
          {String? accountId, bool? notification}) =>
      (super.noSuchMethod(
              Invocation.method(#getAccountChannel, [],
                  {#accountId: accountId, #notification: notification}),
              returnValue:
                  _FakeIWebSocketsChannel<_i21.PleromaWebSocketsEvent>())
          as _i7.IWebSocketsChannel<_i21.PleromaWebSocketsEvent>);
  @override
  _i7.IWebSocketsChannel<_i21.PleromaWebSocketsEvent> getMyAccountChannel(
          {bool? notification, bool? chat}) =>
      (super.noSuchMethod(
              Invocation.method(#getMyAccountChannel, [],
                  {#notification: notification, #chat: chat}),
              returnValue:
                  _FakeIWebSocketsChannel<_i21.PleromaWebSocketsEvent>())
          as _i7.IWebSocketsChannel<_i21.PleromaWebSocketsEvent>);
  @override
  _i7.IWebSocketsChannel<_i21.PleromaWebSocketsEvent> getDirectChannel(
          {String? accountId}) =>
      (super.noSuchMethod(
              Invocation.method(#getDirectChannel, [], {#accountId: accountId}),
              returnValue:
                  _FakeIWebSocketsChannel<_i21.PleromaWebSocketsEvent>())
          as _i7.IWebSocketsChannel<_i21.PleromaWebSocketsEvent>);
  @override
  _i6.WebSocketsEvent eventParser(Map<String, dynamic>? json) =>
      (super.noSuchMethod(Invocation.method(#eventParser, [json]),
          returnValue: _FakeWebSocketsEvent()) as _i6.WebSocketsEvent);
  @override
  void addDisposable(
          {_i15.IDisposable? disposable,
          _i9.StreamSubscription<dynamic>? streamSubscription,
          _i16.TextEditingController? textEditingController,
          _i17.ScrollController? scrollController,
          _i18.FocusNode? focusNode,
          _i19.Subject<dynamic>? subject,
          _i9.StreamController<dynamic>? streamController,
          _i9.Timer? timer,
          _i9.FutureOr<dynamic>? Function()? custom}) =>
      super.noSuchMethod(
          Invocation.method(#addDisposable, [], {
            #disposable: disposable,
            #streamSubscription: streamSubscription,
            #textEditingController: textEditingController,
            #scrollController: scrollController,
            #focusNode: focusNode,
            #subject: subject,
            #streamController: streamController,
            #timer: timer,
            #custom: custom
          }),
          returnValueForMissingStub: null);
  @override
  _i9.Future<dynamic> dispose() =>
      (super.noSuchMethod(Invocation.method(#dispose, []),
          returnValue: Future<dynamic>.value(null)) as _i9.Future<dynamic>);
}
