import 'package:fedi/app/database/app_database.dart';

DbAccount createTestAccount(String seed) => DbAccount(
      id: null,
      remoteId: seed + "remoteId1",
      username: seed + "username1",
      url: seed + "url1",
      note: seed + "note1",
      locked: true,
      headerStatic: seed + "headerStatic1",
      header: seed + "header1",
      followingCount: seed.hashCode + 11,
      followersCount: seed.hashCode + 12,
      statusesCount: seed.hashCode + 13,
      displayName: seed + "displayName1",
      createdAt: DateTime(seed.hashCode + 11),
      avatarStatic: seed + "avatarStatic1",
      avatar: seed + "avatar1",
      acct: seed + "acct1",
      lastStatusAt: DateTime(12),
      bot: false,
      fields: null,
      emojis: null,
      source: null,
      pleromaTags: null,
      pleromaRelationship: null,
      pleromaIsAdmin: true,
      pleromaIsModerator: false,
      pleromaConfirmationPending: true,
      pleromaHideFavorites: false,
      pleromaHideFollowers: true,
      pleromaHideFollows: false,
      pleromaHideFollowersCount: true,
      pleromaHideFollowsCount: false,
      pleromaChatToken: seed + "pleromaChatToken",
      pleromaDeactivated: false,
      pleromaAllowFollowingMove: true,
      pleromaUnreadConversationCount: 14,
      pleromaSkipThreadContainment: true,
      pleromaNotificationSettings: null,
    );
