name: fediverse_api_login_cmd
version: 1.0.8

description: Common code for all fediverse_api_login_cmd extension packages
homepage: https://github.com/Big-Fig/Fediverse.app
repository: https://github.com/Big-Fig/Fediverse.app

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  easy_dispose: ^1.1.0
  puppeteer: ^2.2.1
  http: ^0.13.3
  args: ^2.0.0
  logging: ^1.0.2
  fediverse_api:
    git:
      url: https://github.com/Big-Fig/Fediverse.app.git
      path: packages/fediverse_api
  freezed_annotation: ^0.14.3


dev_dependencies:
  # test utils
  test: ^1.17.9
  # mock utils
  mockito: ^5.0.16
  # additional linters
  dart_code_metrics: ^4.3.3
  lints: 1.0.1
  freezed: ^0.14.5
  build_runner: ^2.1.2
  # helper to specify all rules in one line
  all_lint_rules_community: ^0.0.4