# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

    lane :screenshots do
        frameit(
        path: "./fastlane/screenshots",
        )
    end

    lane :update_metadata do
        deliver(
            submit_for_review: false,
            automatic_release: false,
            skip_metadata: false,
            skip_screenshots: true,
            skip_binary_upload: true,
        )
    end

    lane :update_screenshots do
        deliver(
            submit_for_review: false,
            automatic_release: false,
            skip_metadata: true,
            skip_screenshots: false,
            skip_binary_upload: true,
            overwrite_screenshots: true,
        )
    end

#  desc "Push a new beta build to TestFlight"
#  lane :beta do
# we increment build numbers in Runner & Share extension manually
#    increment_build_number(xcodeproj: "Runner.xcodeproj")
#    sync_code_signing(type: "appstore")
#    build_app(workspace: "Runner.xcworkspace", scheme: "prod")
#    upload_to_testflight
#  end
end
