// Mocks generated by Mockito 5.0.5 from annotations
// in fedi/test/app/chat/message/chat_message_bloc_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i12;

import 'package:fedi/app/account/account_model.dart' as _i10;
import 'package:fedi/app/account/my/my_account_bloc_impl.dart' as _i24;
import 'package:fedi/app/account/my/my_account_local_preference_bloc.dart'
    as _i6;
import 'package:fedi/app/account/my/my_account_model.dart' as _i25;
import 'package:fedi/app/account/repository/account_repository.dart' as _i8;
import 'package:fedi/app/auth/instance/auth_instance_model.dart' as _i9;
import 'package:fedi/app/chat/message/chat_message_model.dart' as _i29;
import 'package:fedi/app/instance/location/instance_location_model.dart'
    as _i26;
import 'package:fedi/app/status/status_model.dart' as _i27;
import 'package:fedi/disposable/disposable.dart' as _i16;
import 'package:fedi/pleroma/api/account/auth/pleroma_auth_account_service_impl.dart'
    as _i21;
import 'package:fedi/pleroma/api/account/my/pleroma_my_account_model.dart' as _i28;
import 'package:fedi/pleroma/api/account/my/pleroma_my_account_service.dart' as _i7;
import 'package:fedi/pleroma/api/account/pleroma_account_model.dart' as _i5;
import 'package:fedi/pleroma/api/pleroma_api_service.dart' as _i13;
import 'package:fedi/pleroma/api/chat/pleroma_chat_model.dart' as _i3;
import 'package:fedi/pleroma/api/chat/pleroma_chat_service_impl.dart' as _i11;
import 'package:fedi/pleroma/api/list/pleroma_list_model.dart' as _i22;
import 'package:fedi/pleroma/api/pagination/pleroma_pagination_model.dart' as _i15;
import 'package:fedi/pleroma/api/rest/auth/pleroma_auth_rest_service.dart' as _i2;
import 'package:fedi/pleroma/api/rest/pleroma_rest_service.dart' as _i4;
import 'package:fedi/pleroma/api/status/pleroma_status_model.dart' as _i23;
import 'package:flutter/src/widgets/editable_text.dart' as _i17;
import 'package:flutter/src/widgets/focus_manager.dart' as _i19;
import 'package:flutter/src/widgets/scroll_controller.dart' as _i18;
import 'package:http/src/response.dart' as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rxdart/src/subjects/subject.dart' as _i20;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeIPleromaAuthRestService extends _i1.Fake
    implements _i2.IPleromaAuthRestService {}

class _FakeIPleromaChat extends _i1.Fake implements _i3.IPleromaChat {}

class _FakeIPleromaChatMessage extends _i1.Fake
    implements _i3.IPleromaChatMessage {}

class _FakeIPleromaRestService extends _i1.Fake
    implements _i4.IPleromaRestService {}

class _FakeIPleromaAccountRelationship extends _i1.Fake
    implements _i5.IPleromaAccountRelationship {}

class _FakeIPleromaAccount extends _i1.Fake implements _i5.IPleromaAccount {}

class _FakeIMyAccountLocalPreferenceBloc extends _i1.Fake
    implements _i6.IMyAccountLocalPreferenceBloc {}

class _FakeIPleromaMyAccountService extends _i1.Fake
    implements _i7.IPleromaMyAccountService {}

class _FakeIAccountRepository extends _i1.Fake
    implements _i8.IAccountRepository {}

class _FakeAuthInstance extends _i1.Fake implements _i9.AuthInstance {}

class _FakeIAccount extends _i1.Fake implements _i10.IAccount {}

/// A class which mocks [PleromaChatService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPleromaChatService extends _i1.Mock
    implements _i11.PleromaChatService {
  MockPleromaChatService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get chatRelativeUrlPath =>
      (super.noSuchMethod(Invocation.getter(#chatRelativeUrlPath),
          returnValue: '') as String);
  @override
  _i2.IPleromaAuthRestService get restService =>
      (super.noSuchMethod(Invocation.getter(#restService),
              returnValue: _FakeIPleromaAuthRestService())
          as _i2.IPleromaAuthRestService);
  @override
  _i12.Stream<_i13.PleromaApiState> get pleromaApiStateStream =>
      (super.noSuchMethod(Invocation.getter(#pleromaApiStateStream),
              returnValue: Stream<_i13.PleromaApiState>.empty())
          as _i12.Stream<_i13.PleromaApiState>);
  @override
  _i13.PleromaApiState get pleromaApiState =>
      (super.noSuchMethod(Invocation.getter(#pleromaApiState),
          returnValue: _i13.PleromaApiState.validAuth) as _i13.PleromaApiState);
  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);
  @override
  _i12.Stream<bool> get isConnectedStream =>
      (super.noSuchMethod(Invocation.getter(#isConnectedStream),
          returnValue: Stream<bool>.empty()) as _i12.Stream<bool>);
  @override
  bool get isMastodon =>
      (super.noSuchMethod(Invocation.getter(#isMastodon), returnValue: false)
          as bool);
  @override
  bool get isPleroma =>
      (super.noSuchMethod(Invocation.getter(#isPleroma), returnValue: false)
          as bool);
  @override
  bool get isDisposed =>
      (super.noSuchMethod(Invocation.getter(#isDisposed), returnValue: false)
          as bool);
  @override
  set isDisposed(bool? _isDisposed) =>
      super.noSuchMethod(Invocation.setter(#isDisposed, _isDisposed),
          returnValueForMissingStub: null);
  @override
  List<_i3.IPleromaChat> parseChatListResponse(_i14.Response? httpResponse) =>
      (super.noSuchMethod(
          Invocation.method(#parseChatListResponse, [httpResponse]),
          returnValue: <_i3.IPleromaChat>[]) as List<_i3.IPleromaChat>);
  @override
  _i3.IPleromaChat parseChatResponse(_i14.Response? httpResponse) =>
      (super.noSuchMethod(Invocation.method(#parseChatResponse, [httpResponse]),
          returnValue: _FakeIPleromaChat()) as _i3.IPleromaChat);
  @override
  List<_i3.IPleromaChatMessage> parseChatMessageListResponse(
          _i14.Response? httpResponse) =>
      (super.noSuchMethod(
              Invocation.method(#parseChatMessageListResponse, [httpResponse]),
              returnValue: <_i3.IPleromaChatMessage>[])
          as List<_i3.IPleromaChatMessage>);
  @override
  _i3.IPleromaChatMessage parseChatMessageResponse(
          _i14.Response? httpResponse) =>
      (super.noSuchMethod(
          Invocation.method(#parseChatMessageResponse, [httpResponse]),
          returnValue: _FakeIPleromaChatMessage()) as _i3.IPleromaChatMessage);
  @override
  _i12.Future<List<_i3.IPleromaChat>> getChats(
          {_i15.IPleromaPaginationRequest? pagination}) =>
      (super.noSuchMethod(
              Invocation.method(#getChats, [], {#pagination: pagination}),
              returnValue:
                  Future<List<_i3.IPleromaChat>>.value(<_i3.IPleromaChat>[]))
          as _i12.Future<List<_i3.IPleromaChat>>);
  @override
  _i12.Future<List<_i3.IPleromaChatMessage>> getChatMessages(
          {String? chatId, _i15.IPleromaPaginationRequest? pagination}) =>
      (super.noSuchMethod(
          Invocation.method(
              #getChatMessages, [], {#chatId: chatId, #pagination: pagination}),
          returnValue: Future<List<_i3.IPleromaChatMessage>>.value(
              <_i3.IPleromaChatMessage>[])) as _i12
          .Future<List<_i3.IPleromaChatMessage>>);
  @override
  _i12.Future<_i3.IPleromaChat> markChatAsRead(
          {String? chatId, String? lastReadChatMessageId}) =>
      (super.noSuchMethod(
              Invocation.method(#markChatAsRead, [], {
                #chatId: chatId,
                #lastReadChatMessageId: lastReadChatMessageId
              }),
              returnValue: Future<_i3.IPleromaChat>.value(_FakeIPleromaChat()))
          as _i12.Future<_i3.IPleromaChat>);
  @override
  _i12.Future<_i3.IPleromaChat> getOrCreateChatByAccountId(
          {String? accountId}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getOrCreateChatByAccountId, [], {#accountId: accountId}),
              returnValue: Future<_i3.IPleromaChat>.value(_FakeIPleromaChat()))
          as _i12.Future<_i3.IPleromaChat>);
  @override
  _i12.Future<_i3.IPleromaChat> getChat({String? id}) =>
      (super.noSuchMethod(Invocation.method(#getChat, [], {#id: id}),
              returnValue: Future<_i3.IPleromaChat>.value(_FakeIPleromaChat()))
          as _i12.Future<_i3.IPleromaChat>);
  @override
  _i12.Future<_i3.IPleromaChatMessage> sendMessage(
          {String? chatId, _i3.IPleromaChatMessageSendData? data}) =>
      (super.noSuchMethod(
          Invocation.method(#sendMessage, [], {#chatId: chatId, #data: data}),
          returnValue: Future<_i3.IPleromaChatMessage>.value(
              _FakeIPleromaChatMessage())) as _i12
          .Future<_i3.IPleromaChatMessage>);
  @override
  _i12.Future<dynamic> deleteChatMessage(
          {String? chatMessageRemoteId, String? chatId}) =>
      (super.noSuchMethod(
          Invocation.method(#deleteChatMessage, [],
              {#chatMessageRemoteId: chatMessageRemoteId, #chatId: chatId}),
          returnValue: Future<dynamic>.value(null)) as _i12.Future<dynamic>);
  @override
  void addDisposable(
          {_i16.IDisposable? disposable,
          _i12.StreamSubscription<dynamic>? streamSubscription,
          _i17.TextEditingController? textEditingController,
          _i18.ScrollController? scrollController,
          _i19.FocusNode? focusNode,
          _i20.Subject<dynamic>? subject,
          _i12.StreamController<dynamic>? streamController,
          _i12.Timer? timer,
          _i12.FutureOr<dynamic>? Function()? custom}) =>
      super.noSuchMethod(
          Invocation.method(#addDisposable, [], {
            #disposable: disposable,
            #streamSubscription: streamSubscription,
            #textEditingController: textEditingController,
            #scrollController: scrollController,
            #focusNode: focusNode,
            #subject: subject,
            #streamController: streamController,
            #timer: timer,
            #custom: custom
          }),
          returnValueForMissingStub: null);
  @override
  _i12.Future<dynamic> dispose() =>
      (super.noSuchMethod(Invocation.method(#dispose, []),
          returnValue: Future<dynamic>.value(null)) as _i12.Future<dynamic>);
}

/// A class which mocks [PleromaAuthAccountService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPleromaAuthAccountService extends _i1.Mock
    implements _i21.PleromaAuthAccountService {
  MockPleromaAuthAccountService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get accountReportRelativeUrlPath =>
      (super.noSuchMethod(Invocation.getter(#accountReportRelativeUrlPath),
          returnValue: '') as String);
  @override
  _i2.IPleromaAuthRestService get authRestService =>
      (super.noSuchMethod(Invocation.getter(#authRestService),
              returnValue: _FakeIPleromaAuthRestService())
          as _i2.IPleromaAuthRestService);
  @override
  bool get isPleroma =>
      (super.noSuchMethod(Invocation.getter(#isPleroma), returnValue: false)
          as bool);
  @override
  _i12.Stream<_i13.PleromaApiState> get pleromaApiStateStream =>
      (super.noSuchMethod(Invocation.getter(#pleromaApiStateStream),
              returnValue: Stream<_i13.PleromaApiState>.empty())
          as _i12.Stream<_i13.PleromaApiState>);
  @override
  _i13.PleromaApiState get pleromaApiState =>
      (super.noSuchMethod(Invocation.getter(#pleromaApiState),
          returnValue: _i13.PleromaApiState.validAuth) as _i13.PleromaApiState);
  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);
  @override
  _i12.Stream<bool> get isConnectedStream =>
      (super.noSuchMethod(Invocation.getter(#isConnectedStream),
          returnValue: Stream<bool>.empty()) as _i12.Stream<bool>);
  @override
  bool get isMastodon =>
      (super.noSuchMethod(Invocation.getter(#isMastodon), returnValue: false)
          as bool);
  @override
  String get accountRelativeUrlPath =>
      (super.noSuchMethod(Invocation.getter(#accountRelativeUrlPath),
          returnValue: '') as String);
  @override
  String get pleromaAccountRelativeUrlPath =>
      (super.noSuchMethod(Invocation.getter(#pleromaAccountRelativeUrlPath),
          returnValue: '') as String);
  @override
  _i4.IPleromaRestService get restService =>
      (super.noSuchMethod(Invocation.getter(#restService),
          returnValue: _FakeIPleromaRestService()) as _i4.IPleromaRestService);
  @override
  bool get isDisposed =>
      (super.noSuchMethod(Invocation.getter(#isDisposed), returnValue: false)
          as bool);
  @override
  set isDisposed(bool? _isDisposed) =>
      super.noSuchMethod(Invocation.setter(#isDisposed, _isDisposed),
          returnValueForMissingStub: null);
  @override
  _i12.Future<List<_i5.IPleromaAccountRelationship>>
      getRelationshipWithAccounts({List<String>? remoteAccountIds}) =>
          (super.noSuchMethod(
              Invocation.method(#getRelationshipWithAccounts, [],
                  {#remoteAccountIds: remoteAccountIds}),
              returnValue: Future<List<_i5.IPleromaAccountRelationship>>.value(
                  <_i5.IPleromaAccountRelationship>[])) as _i12
              .Future<List<_i5.IPleromaAccountRelationship>>);
  @override
  _i12.Future<_i5.IPleromaAccountRelationship> blockAccount(
          {String? accountRemoteId}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #blockAccount, [], {#accountRemoteId: accountRemoteId}),
              returnValue: Future<_i5.IPleromaAccountRelationship>.value(
                  _FakeIPleromaAccountRelationship()))
          as _i12.Future<_i5.IPleromaAccountRelationship>);
  @override
  _i12.Future<_i5.IPleromaAccountRelationship> followAccount(
          {String? accountRemoteId}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #followAccount, [], {#accountRemoteId: accountRemoteId}),
              returnValue: Future<_i5.IPleromaAccountRelationship>.value(
                  _FakeIPleromaAccountRelationship()))
          as _i12.Future<_i5.IPleromaAccountRelationship>);
  @override
  _i12.Future<_i5.IPleromaAccountRelationship> muteAccount(
          {String? accountRemoteId,
          bool? notifications,
          int? expireDurationInSeconds}) =>
      (super.noSuchMethod(
              Invocation.method(#muteAccount, [], {
                #accountRemoteId: accountRemoteId,
                #notifications: notifications,
                #expireDurationInSeconds: expireDurationInSeconds
              }),
              returnValue: Future<_i5.IPleromaAccountRelationship>.value(
                  _FakeIPleromaAccountRelationship()))
          as _i12.Future<_i5.IPleromaAccountRelationship>);
  @override
  _i12.Future<_i5.IPleromaAccountRelationship> pinAccount(
          {String? accountRemoteId}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #pinAccount, [], {#accountRemoteId: accountRemoteId}),
              returnValue: Future<_i5.IPleromaAccountRelationship>.value(
                  _FakeIPleromaAccountRelationship()))
          as _i12.Future<_i5.IPleromaAccountRelationship>);
  @override
  _i12.Future<_i5.IPleromaAccountRelationship> unBlockAccount(
          {String? accountRemoteId}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #unBlockAccount, [], {#accountRemoteId: accountRemoteId}),
              returnValue: Future<_i5.IPleromaAccountRelationship>.value(
                  _FakeIPleromaAccountRelationship()))
          as _i12.Future<_i5.IPleromaAccountRelationship>);
  @override
  _i12.Future<_i5.IPleromaAccountRelationship> unFollowAccount(
          {String? accountRemoteId}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #unFollowAccount, [], {#accountRemoteId: accountRemoteId}),
              returnValue: Future<_i5.IPleromaAccountRelationship>.value(
                  _FakeIPleromaAccountRelationship()))
          as _i12.Future<_i5.IPleromaAccountRelationship>);
  @override
  _i12.Future<_i5.IPleromaAccountRelationship> unMuteAccount(
          {String? accountRemoteId}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #unMuteAccount, [], {#accountRemoteId: accountRemoteId}),
              returnValue: Future<_i5.IPleromaAccountRelationship>.value(
                  _FakeIPleromaAccountRelationship()))
          as _i12.Future<_i5.IPleromaAccountRelationship>);
  @override
  _i12.Future<_i5.IPleromaAccountRelationship> unPinAccount(
          {String? accountRemoteId}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #unPinAccount, [], {#accountRemoteId: accountRemoteId}),
              returnValue: Future<_i5.IPleromaAccountRelationship>.value(
                  _FakeIPleromaAccountRelationship()))
          as _i12.Future<_i5.IPleromaAccountRelationship>);
  @override
  _i12.Future<List<_i5.IPleromaAccountIdentityProof>> getAccountIdentifyProofs(
          {String? accountRemoteId}) =>
      (super.noSuchMethod(
              Invocation.method(#getAccountIdentifyProofs, [],
                  {#accountRemoteId: accountRemoteId}),
              returnValue: Future<List<_i5.IPleromaAccountIdentityProof>>.value(
                  <_i5.IPleromaAccountIdentityProof>[]))
          as _i12.Future<List<_i5.IPleromaAccountIdentityProof>>);
  @override
  _i12.Future<List<_i22.IPleromaList>> getListsWithAccount(
          {String? accountRemoteId}) =>
      (super.noSuchMethod(
          Invocation.method(
              #getListsWithAccount, [], {#accountRemoteId: accountRemoteId}),
          returnValue: Future<List<_i22.IPleromaList>>.value(
              <_i22.IPleromaList>[])) as _i12.Future<List<_i22.IPleromaList>>);
  @override
  _i12.Future<List<_i5.IPleromaAccount>> search(
          {String? query,
          bool? resolve,
          bool? following,
          _i15.IPleromaPaginationRequest? pagination}) =>
      (super.noSuchMethod(
              Invocation.method(#search, [], {
                #query: query,
                #resolve: resolve,
                #following: following,
                #pagination: pagination
              }),
              returnValue: Future<List<_i5.IPleromaAccount>>.value(
                  <_i5.IPleromaAccount>[]))
          as _i12.Future<List<_i5.IPleromaAccount>>);
  @override
  _i12.Future<bool> reportAccount(
          {_i5.IPleromaAccountReportRequest? reportRequest}) =>
      (super.noSuchMethod(
          Invocation.method(
              #reportAccount, [], {#reportRequest: reportRequest}),
          returnValue: Future<bool>.value(false)) as _i12.Future<bool>);
  @override
  _i12.Future<dynamic> blockDomain({String? domain}) => (super.noSuchMethod(
      Invocation.method(#blockDomain, [], {#domain: domain}),
      returnValue: Future<dynamic>.value(null)) as _i12.Future<dynamic>);
  @override
  _i12.Future<dynamic> unBlockDomain({String? domain}) => (super.noSuchMethod(
      Invocation.method(#unBlockDomain, [], {#domain: domain}),
      returnValue: Future<dynamic>.value(null)) as _i12.Future<dynamic>);
  @override
  _i12.Future<_i5.IPleromaAccountRelationship> subscribeAccount(
          {String? accountRemoteId}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #subscribeAccount, [], {#accountRemoteId: accountRemoteId}),
              returnValue: Future<_i5.IPleromaAccountRelationship>.value(
                  _FakeIPleromaAccountRelationship()))
          as _i12.Future<_i5.IPleromaAccountRelationship>);
  @override
  _i12.Future<_i5.IPleromaAccountRelationship> unSubscribeAccount(
          {String? accountRemoteId}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #unSubscribeAccount, [], {#accountRemoteId: accountRemoteId}),
              returnValue: Future<_i5.IPleromaAccountRelationship>.value(
                  _FakeIPleromaAccountRelationship()))
          as _i12.Future<_i5.IPleromaAccountRelationship>);
  @override
  List<_i5.PleromaAccount> parseAccountListResponse(
          _i14.Response? httpResponse) =>
      (super.noSuchMethod(
          Invocation.method(#parseAccountListResponse, [httpResponse]),
          returnValue: <_i5.PleromaAccount>[]) as List<_i5.PleromaAccount>);
  @override
  List<_i5.IPleromaAccountIdentityProof> parseAccountAccountIdentityProofList(
          _i14.Response? httpResponse) =>
      (super.noSuchMethod(
              Invocation.method(
                  #parseAccountAccountIdentityProofList, [httpResponse]),
              returnValue: <_i5.IPleromaAccountIdentityProof>[])
          as List<_i5.IPleromaAccountIdentityProof>);
  @override
  List<_i22.IPleromaList> parseListList(_i14.Response? httpResponse) =>
      (super.noSuchMethod(Invocation.method(#parseListList, [httpResponse]),
          returnValue: <_i22.IPleromaList>[]) as List<_i22.IPleromaList>);
  @override
  List<_i23.IPleromaStatus> parseStatusListResponse(
          _i14.Response? httpResponse) =>
      (super.noSuchMethod(
          Invocation.method(#parseStatusListResponse, [httpResponse]),
          returnValue: <_i23.IPleromaStatus>[]) as List<_i23.IPleromaStatus>);
  @override
  _i5.IPleromaAccountRelationship parseAccountRelationshipResponse(
          _i14.Response? httpResponse) =>
      (super.noSuchMethod(
          Invocation.method(#parseAccountRelationshipResponse, [httpResponse]),
          returnValue:
              _FakeIPleromaAccountRelationship()) as _i5
          .IPleromaAccountRelationship);
  @override
  List<_i5.IPleromaAccountRelationship> parseAccountRelationshipResponseList(
          _i14.Response? httpResponse) =>
      (super.noSuchMethod(
              Invocation.method(
                  #parseAccountRelationshipResponseList, [httpResponse]),
              returnValue: <_i5.IPleromaAccountRelationship>[])
          as List<_i5.IPleromaAccountRelationship>);
  @override
  _i5.IPleromaAccount parseAccountResponse(_i14.Response? httpResponse) =>
      (super.noSuchMethod(
          Invocation.method(#parseAccountResponse, [httpResponse]),
          returnValue: _FakeIPleromaAccount()) as _i5.IPleromaAccount);
  @override
  _i12.Future<List<_i5.IPleromaAccount>> getAccountFollowings(
          {String? accountRemoteId,
          _i15.IPleromaPaginationRequest? pagination}) =>
      (super.noSuchMethod(
              Invocation.method(#getAccountFollowings, [],
                  {#accountRemoteId: accountRemoteId, #pagination: pagination}),
              returnValue: Future<List<_i5.IPleromaAccount>>.value(
                  <_i5.IPleromaAccount>[]))
          as _i12.Future<List<_i5.IPleromaAccount>>);
  @override
  _i12.Future<_i5.IPleromaAccount> getAccount({String? accountRemoteId}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getAccount, [], {#accountRemoteId: accountRemoteId}),
              returnValue:
                  Future<_i5.IPleromaAccount>.value(_FakeIPleromaAccount()))
          as _i12.Future<_i5.IPleromaAccount>);
  @override
  _i12.Future<List<_i5.PleromaAccount>> getAccountFollowers(
          {String? accountRemoteId,
          _i15.IPleromaPaginationRequest? pagination}) =>
      (super.noSuchMethod(
              Invocation.method(#getAccountFollowers, [],
                  {#accountRemoteId: accountRemoteId, #pagination: pagination}),
              returnValue: Future<List<_i5.PleromaAccount>>.value(
                  <_i5.PleromaAccount>[]))
          as _i12.Future<List<_i5.PleromaAccount>>);
  @override
  _i12.Future<List<_i23.IPleromaStatus>> getAccountStatuses(
          {String? accountRemoteId,
          String? tagged,
          bool? pinned,
          bool? excludeReplies,
          bool? excludeReblogs,
          List<String>? excludeVisibilities,
          bool? withMuted,
          bool? onlyWithMedia,
          _i15.IPleromaPaginationRequest? pagination}) =>
      (super.noSuchMethod(
              Invocation.method(#getAccountStatuses, [], {
                #accountRemoteId: accountRemoteId,
                #tagged: tagged,
                #pinned: pinned,
                #excludeReplies: excludeReplies,
                #excludeReblogs: excludeReblogs,
                #excludeVisibilities: excludeVisibilities,
                #withMuted: withMuted,
                #onlyWithMedia: onlyWithMedia,
                #pagination: pagination
              }),
              returnValue: Future<List<_i23.IPleromaStatus>>.value(
                  <_i23.IPleromaStatus>[]))
          as _i12.Future<List<_i23.IPleromaStatus>>);
  @override
  _i12.Future<List<_i23.IPleromaStatus>> getAccountFavouritedStatuses(
          {String? accountRemoteId,
          _i15.IPleromaPaginationRequest? pagination}) =>
      (super.noSuchMethod(
              Invocation.method(#getAccountFavouritedStatuses, [],
                  {#accountRemoteId: accountRemoteId, #pagination: pagination}),
              returnValue: Future<List<_i23.IPleromaStatus>>.value(
                  <_i23.IPleromaStatus>[]))
          as _i12.Future<List<_i23.IPleromaStatus>>);
  @override
  void addDisposable(
          {_i16.IDisposable? disposable,
          _i12.StreamSubscription<dynamic>? streamSubscription,
          _i17.TextEditingController? textEditingController,
          _i18.ScrollController? scrollController,
          _i19.FocusNode? focusNode,
          _i20.Subject<dynamic>? subject,
          _i12.StreamController<dynamic>? streamController,
          _i12.Timer? timer,
          _i12.FutureOr<dynamic>? Function()? custom}) =>
      super.noSuchMethod(
          Invocation.method(#addDisposable, [], {
            #disposable: disposable,
            #streamSubscription: streamSubscription,
            #textEditingController: textEditingController,
            #scrollController: scrollController,
            #focusNode: focusNode,
            #subject: subject,
            #streamController: streamController,
            #timer: timer,
            #custom: custom
          }),
          returnValueForMissingStub: null);
  @override
  _i12.Future<dynamic> dispose() =>
      (super.noSuchMethod(Invocation.method(#dispose, []),
          returnValue: Future<dynamic>.value(null)) as _i12.Future<dynamic>);
}

/// A class which mocks [MyAccountBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMyAccountBloc extends _i1.Mock implements _i24.MyAccountBloc {
  MockMyAccountBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.IMyAccountLocalPreferenceBloc get myAccountLocalPreferenceBloc =>
      (super.noSuchMethod(Invocation.getter(#myAccountLocalPreferenceBloc),
              returnValue: _FakeIMyAccountLocalPreferenceBloc())
          as _i6.IMyAccountLocalPreferenceBloc);
  @override
  _i7.IPleromaMyAccountService get pleromaMyAccountService =>
      (super.noSuchMethod(Invocation.getter(#pleromaMyAccountService),
              returnValue: _FakeIPleromaMyAccountService())
          as _i7.IPleromaMyAccountService);
  @override
  _i8.IAccountRepository get accountRepository =>
      (super.noSuchMethod(Invocation.getter(#accountRepository),
          returnValue: _FakeIAccountRepository()) as _i8.IAccountRepository);
  @override
  _i9.AuthInstance get instance =>
      (super.noSuchMethod(Invocation.getter(#instance),
          returnValue: _FakeAuthInstance()) as _i9.AuthInstance);
  @override
  bool get isLocalCacheExist =>
      (super.noSuchMethod(Invocation.getter(#isLocalCacheExist),
          returnValue: false) as bool);
  @override
  _i12.Stream<_i25.IMyAccount?> get myAccountStream =>
      (super.noSuchMethod(Invocation.getter(#myAccountStream),
              returnValue: Stream<_i25.IMyAccount?>.empty())
          as _i12.Stream<_i25.IMyAccount?>);
  @override
  _i12.Stream<_i10.IAccount> get accountStream =>
      (super.noSuchMethod(Invocation.getter(#accountStream),
              returnValue: Stream<_i10.IAccount>.empty())
          as _i12.Stream<_i10.IAccount>);
  @override
  _i10.IAccount get account => (super.noSuchMethod(Invocation.getter(#account),
      returnValue: _FakeIAccount()) as _i10.IAccount);
  @override
  _i5.IPleromaAccountRelationship get relationship =>
      (super.noSuchMethod(Invocation.getter(#relationship),
              returnValue: _FakeIPleromaAccountRelationship())
          as _i5.IPleromaAccountRelationship);
  @override
  _i12.Stream<_i5.IPleromaAccountRelationship> get relationshipStream =>
      (super.noSuchMethod(Invocation.getter(#relationshipStream),
              returnValue: Stream<_i5.IPleromaAccountRelationship>.empty())
          as _i12.Stream<_i5.IPleromaAccountRelationship>);
  @override
  _i26.InstanceLocation get instanceLocation =>
      (super.noSuchMethod(Invocation.getter(#instanceLocation),
          returnValue: _i26.InstanceLocation.local) as _i26.InstanceLocation);
  @override
  bool get isDisposed =>
      (super.noSuchMethod(Invocation.getter(#isDisposed), returnValue: false)
          as bool);
  @override
  set isDisposed(bool? _isDisposed) =>
      super.noSuchMethod(Invocation.setter(#isDisposed, _isDisposed),
          returnValueForMissingStub: null);
  @override
  _i12.Future<_i5.IPleromaAccountRelationship> toggleBlock() =>
      (super.noSuchMethod(Invocation.method(#toggleBlock, []),
              returnValue: Future<_i5.IPleromaAccountRelationship>.value(
                  _FakeIPleromaAccountRelationship()))
          as _i12.Future<_i5.IPleromaAccountRelationship>);
  @override
  _i12.Future<_i5.IPleromaAccountRelationship> toggleFollow() =>
      (super.noSuchMethod(Invocation.method(#toggleFollow, []),
              returnValue: Future<_i5.IPleromaAccountRelationship>.value(
                  _FakeIPleromaAccountRelationship()))
          as _i12.Future<_i5.IPleromaAccountRelationship>);
  @override
  _i12.Future<dynamic> refreshFromNetwork({bool? isNeedPreFetchRelationship}) =>
      (super.noSuchMethod(
          Invocation.method(#refreshFromNetwork, [],
              {#isNeedPreFetchRelationship: isNeedPreFetchRelationship}),
          returnValue: Future<dynamic>.value(null)) as _i12.Future<dynamic>);
  @override
  bool checkAccountIsMe(_i10.IAccount? account) =>
      (super.noSuchMethod(Invocation.method(#checkAccountIsMe, [account]),
          returnValue: false) as bool);
  @override
  bool checkIsStatusFromMe(_i27.IStatus? status) =>
      (super.noSuchMethod(Invocation.method(#checkIsStatusFromMe, [status]),
          returnValue: false) as bool);
  @override
  _i12.Future<_i5.IPleromaAccountRelationship> togglePin() =>
      (super.noSuchMethod(Invocation.method(#togglePin, []),
              returnValue: Future<_i5.IPleromaAccountRelationship>.value(
                  _FakeIPleromaAccountRelationship()))
          as _i12.Future<_i5.IPleromaAccountRelationship>);
  @override
  _i12.Future<_i5.IPleromaAccountRelationship> toggleBlockDomain() =>
      (super.noSuchMethod(Invocation.method(#toggleBlockDomain, []),
              returnValue: Future<_i5.IPleromaAccountRelationship>.value(
                  _FakeIPleromaAccountRelationship()))
          as _i12.Future<_i5.IPleromaAccountRelationship>);
  @override
  _i12.Future<dynamic> updateMyAccountByMyPleromaAccount(
          _i28.IPleromaMyAccount? pleromaMyAccount) =>
      (super.noSuchMethod(
          Invocation.method(
              #updateMyAccountByMyPleromaAccount, [pleromaMyAccount]),
          returnValue: Future<dynamic>.value(null)) as _i12.Future<dynamic>);
  @override
  _i12.Future<dynamic> updateMyAccountByMyAccount(_i25.IMyAccount? myAccount) =>
      (super.noSuchMethod(
          Invocation.method(#updateMyAccountByMyAccount, [myAccount]),
          returnValue: Future<dynamic>.value(null)) as _i12.Future<dynamic>);
  @override
  _i12.Future<dynamic> decreaseFollowingRequestCount() =>
      (super.noSuchMethod(Invocation.method(#decreaseFollowingRequestCount, []),
          returnValue: Future<dynamic>.value(null)) as _i12.Future<dynamic>);
  @override
  bool checkIsChatMessageFromMe(_i29.IChatMessage? chatMessage) => (super
      .noSuchMethod(Invocation.method(#checkIsChatMessageFromMe, [chatMessage]),
          returnValue: false) as bool);
  @override
  _i12.Future<_i5.IPleromaAccountRelationship> mute(
          {bool? notifications, Duration? duration}) =>
      (super.noSuchMethod(
          Invocation.method(
              #mute, [], {#notifications: notifications, #duration: duration}),
          returnValue: Future<_i5.IPleromaAccountRelationship>.value(
              _FakeIPleromaAccountRelationship())) as _i12
          .Future<_i5.IPleromaAccountRelationship>);
  @override
  _i12.Future<_i5.IPleromaAccountRelationship> unMute() =>
      (super.noSuchMethod(Invocation.method(#unMute, []),
              returnValue: Future<_i5.IPleromaAccountRelationship>.value(
                  _FakeIPleromaAccountRelationship()))
          as _i12.Future<_i5.IPleromaAccountRelationship>);
  @override
  _i12.Future<_i5.IPleromaAccountRelationship> subscribe() =>
      (super.noSuchMethod(Invocation.method(#subscribe, []),
              returnValue: Future<_i5.IPleromaAccountRelationship>.value(
                  _FakeIPleromaAccountRelationship()))
          as _i12.Future<_i5.IPleromaAccountRelationship>);
  @override
  _i12.Future<_i5.IPleromaAccountRelationship> toggleMute() =>
      (super.noSuchMethod(Invocation.method(#toggleMute, []),
              returnValue: Future<_i5.IPleromaAccountRelationship>.value(
                  _FakeIPleromaAccountRelationship()))
          as _i12.Future<_i5.IPleromaAccountRelationship>);
  @override
  _i12.Future<_i5.IPleromaAccountRelationship> toggleSubscribe() =>
      (super.noSuchMethod(Invocation.method(#toggleSubscribe, []),
              returnValue: Future<_i5.IPleromaAccountRelationship>.value(
                  _FakeIPleromaAccountRelationship()))
          as _i12.Future<_i5.IPleromaAccountRelationship>);
  @override
  _i12.Future<_i5.IPleromaAccountRelationship> unSubscribe() =>
      (super.noSuchMethod(Invocation.method(#unSubscribe, []),
              returnValue: Future<_i5.IPleromaAccountRelationship>.value(
                  _FakeIPleromaAccountRelationship()))
          as _i12.Future<_i5.IPleromaAccountRelationship>);
  @override
  void addDisposable(
          {_i16.IDisposable? disposable,
          _i12.StreamSubscription<dynamic>? streamSubscription,
          _i17.TextEditingController? textEditingController,
          _i18.ScrollController? scrollController,
          _i19.FocusNode? focusNode,
          _i20.Subject<dynamic>? subject,
          _i12.StreamController<dynamic>? streamController,
          _i12.Timer? timer,
          _i12.FutureOr<dynamic>? Function()? custom}) =>
      super.noSuchMethod(
          Invocation.method(#addDisposable, [], {
            #disposable: disposable,
            #streamSubscription: streamSubscription,
            #textEditingController: textEditingController,
            #scrollController: scrollController,
            #focusNode: focusNode,
            #subject: subject,
            #streamController: streamController,
            #timer: timer,
            #custom: custom
          }),
          returnValueForMissingStub: null);
  @override
  _i12.Future<dynamic> dispose() =>
      (super.noSuchMethod(Invocation.method(#dispose, []),
          returnValue: Future<dynamic>.value(null)) as _i12.Future<dynamic>);
}
