name: fediverse_api
version: 1.0.9

description: Common code for all fediverse_api extension packages
homepage: https://github.com/Big-Fig/Fediverse.app
repository: https://github.com/Big-Fig/Fediverse.app

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # Disposable logic
  easy_dispose: ^1.1.0
  easy_dispose_rxdart: ^1.1.0
  http: ^0.13.4
  logging: ^1.0.2
#  path: ^1.8.0
  hive:
    git:
      url: https://github.com/xal/hive
      ref: xal/nested_type_registry_dev
      path: hive
  json_annotation: ^4.3.0
  # WebSockets API mobile implementation
  web_socket_channel: 2.1.0
  freezed_annotation: ^0.15.0
  rxdart: ^0.27.2
  collection: ^1.15.0
  path: ^1.8.0

dev_dependencies:
  test: ^1.19.2
  mockito: ^5.0.16
  # additional linters
  dart_code_metrics: ^4.5.0
  lints: 1.0.1
  freezed: ^0.15.0+1
  build_runner: ^2.1.4
  hive_generator:
    git:
      url: https://github.com/xal/hive
      ref: xal/nested_type_registry_dev
      path: hive_generator
  json_serializable: ^6.0.1
  # helper to specify all rules in one line
  all_lint_rules_community: ^0.0.4

