name: mastodon_api_login_cmd
version: 1.0.9

description: Command line tool for Mastodon Login via Chrome emulation
homepage: https://github.com/Big-Fig/Fediverse.app
repository: https://github.com/Big-Fig/Fediverse.app

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  logging: ^1.0.2
  easy_dispose: ^1.1.0
  fediverse_api:
    path: ../../packages/fediverse_api
#    git:
#      url: https://github.com/Big-Fig/Fediverse.app.git
#      path: packages/fediverse_api
  fediverse_api_login_cmd:
    path: ../../packages/fediverse_api_login_cmd
#    git:
#      url: https://github.com/Big-Fig/Fediverse.app.git
#      path: packages/fediverse_api_login_cmd
  mastodon_api:
    path: ../../packages/mastodon_api
#    git:
#      url: https://github.com/Big-Fig/Fediverse.app.git
#      path: packages/mastodon_api
  freezed_annotation: ^0.15.0
  # helper to specify all rules in one line
  all_lint_rules_community: ^0.0.4

dev_dependencies:
  # test utils
  test: any
  # mock utils
  mockito: ^5.0.16
  # additional linters
  dart_code_metrics: ^4.5.0
  lints: 1.0.1
  freezed: ^0.15.0+1
  build_runner: ^2.1.4

executables:
  mastodon_api_login: main