name: lints
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  unit-test:
    name: Lints check on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:


      # Set up Flutter.
      - name: Clone Flutter repository
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.3'
          channel: 'any'
        # fork version with fvm parsing
        # uses: xal/flutter-action@feature/read-version-from-file-fixes
        # with:
        # parse: 'fvm'

      - run: flutter --version

      # Checkout code and get packages.
      - name: Checkout repository
        uses: actions/checkout@v2

      - run: flutter pub get

      # flutter analyze will fail even if project have `info` messages
      - name: Analyze
        run: flutter analyze