name: lints
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  unit-test:
    name: Lints check on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:


      # Checkout code and get packages.
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Readm FVM config
        uses: kuhnroyal/flutter-fvm-config-action@v1

      - name: Set up Flutter.
        uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}

      - run: flutter --version

      - run: flutter pub get

      # flutter analyze will fail even if project have `info` messages
      - name: Analyze
        run: flutter analyze