name: merge_develop_to_weblate
on:
  push:
    branches:
      - 'develop'
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge develop -> weblate
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: development
          target_branch: weblate
          github_token: ${{ github.token }}