name: regenerate_localization_and_make_pr
on:
  push:
    branches:
      - 'weblate'

jobs:
  unit-test:
    name: Regenerate localization on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:

      # Checkout code and get packages.
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Readm FVM config
        uses: kuhnroyal/flutter-fvm-config-action@v1

      - name: Set up Flutter.
        uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}

      - run: flutter --version

      - name: Install Tools
        run: |
          ./.github/workflows/scripts/install_tools.sh

      - name: Bootstrap Workspace
        # not sure why but bootstrap stuck on GitHub Actions
        # since this project have only one package we can run flutter pub get instead bootstrap
        #        run: flutter pub global run melos bootstrap
        run: flutter pub global run melos exec flutter pub get

      - name: Reset weblate branch
        run: |
          git fetch origin weblate:weblate
          git reset --hard weblate

      - name: Install intl_utils
        run: flutter pub global activate intl_utils

      - name: Generate dart localization code
        run: flutter pub global run melos run generate:intl_utils

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          # we need custom tokes to trigger other workflows on PR
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
          branch: weblate-promotion
          commit-message: Update report
          signoff: true
          delete-branch: false
          title: '[Weblate] Update localization'
          body: |
            Update localization after weblate push
          labels: |
            localization
          team-reviewers: |
            owners
            maintainers
          draft: false

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"