name: regenerate_localization_and_make_pr
on:
  push:
    branches:
      - 'weblate'

jobs:
  unit-test:
    name: Regenerate localization on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:

      # Set up Flutter.
      - name: Clone Flutter repository
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.3'
          channel: 'any'
        # fork version with fvm parsing
        # uses: xal/flutter-action@feature/read-version-from-file-fixes
        # with:
        # parse: 'fvm'

      - run: flutter --version

      # Checkout code and get packages.
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Pub Get Packages
        run: flutter pub get

      - name: Reset weblate branch
        run: |
          git fetch origin weblate:weblate
          git reset --hard weblate

      - name: Install intl_utils
        run: flutter pub global activate intl_utils

      - name: Generate dart localization code
        run: flutter pub global run intl_utils:generate

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          # we need custom tokes to trigger other workflows on PR
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
          branch: weblate-promotion
          commit-message: Update report
          signoff: true
          delete-branch: false
          title: '[Weblate] Update localization'
          body: |
            Update localization after weblate push
          labels: |
            localization
          team-reviewers: |
            owners
            maintainers
          draft: false

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"