name: regenerate_localization
on:
  push:
    branches-ignore:
      - 'master'
      - 'develop'
    paths:
      - '**.arb'

jobs:
  unit-test:
    name: Regenerate localization on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:

      # Set up Flutter.
      - name: Clone Flutter repository
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.3'
          channel: 'any'
        # fork version with fvm parsing
        # uses: xal/flutter-action@feature/read-version-from-file-fixes
        # with:
        # parse: 'fvm'

      - run: flutter --version

      - name: Pub Get Packages
        run: flutter pub get

      # Checkout code and get packages.
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install intl_utils
        run: flutter pub global activate intl_utils

      - name: Generate dart localization code
        run: flutter pub run intl_utils:generate

      # flutter analyze will fail even if project have `info` messages
      - name: Analyze
        run: flutter analyze

      - name: Add files and commit
      - uses: EndBug/add-and-commit@v7
        with:
          add: '.'
          # The message for the commit
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: 'Regenerate localization after *.arb file changes'

          # Whether to push the commit and, if any, its tags to the repo. It can also be used to set the git push arguments (see the paragraph below for more info)
          # Default: true
          push: true