name: unit_tests
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - master

jobs:
  unit-test:
    name: Unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      # needed by flutter-action
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      # Checkout code and get packages.
      - name: Checkout repository
      - uses: actions/checkout@v2

      - name: Readm FVM config
      - uses: kuhnroyal/flutter-fvm-config-action@v1

      - name: Set up Flutter.
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}

      - run: flutter --version

      - run: flutter pub get

      - name: Run Flutter unit tests
        run: flutter test --no-pub --no-null-assertions --no-track-widget-creation -j 10