name: unit_tests_with_coverage
on:
  push:
    branches:
      - master

jobs:
  unit-test:
    name: Unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      # needed by flutter-action
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      # Set up Flutter.
      - name: Clone Flutter repository
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.2'
          channel: 'any'
        # fork version with fvm parsing
        # uses: xal/flutter-action@feature/read-version-from-file-fixes
        # with:
        # parse: 'fvm'

      - run: flutter --version

      # Checkout code and get packages.
      - name: Checkout repository
        uses: actions/checkout@v2

      - run: flutter pub get

      - name: Run Flutter unit tests with coverage
        run: flutter test --coverage --no-pub --no-null-assertions --no-track-widget-creation -j 10 --coverage-path=coverage/lcov_test.info

      - name: Upload to unit tests coverage codecov
        uses: codecov/codecov-action@v1
        with:
          files:
            coverage/lcov_test.info
          flags: unit_tests
          fail_ci_if_error: true


      #       Flutter don't include files in coverage which not touched with tests
      #       so we need to add all files manually
      - name: Generate coverage_helper_test.dart to get totoal coverage
        uses: stelynx/dart-full-coverage@v1.0.5
        with:
          test_file: 'test/coverage_helper_test.dart'
          ignore: '*.g.dart, *_keys.dart'
          package: fedi

      # it is not possible to run all tests with coverage_helper_test due to bad performance
      - name: Run Flutter test for coverage_helper_test.dart
        # step will fail because coverage_helper_test.dart dont have tests
        continue-on-error: true
        run: flutter test --coverage --no-pub --no-null-assertions --no-track-widget-creation -j 10 --coverage-path=coverage/lcov_all.info test/coverage_helper_test.dart

      - name: Upload coverage_helper_test.dart coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          files:
            coverage/lcov_all.info
          flags: all_tests
          fail_ci_if_error: true