name: unit_tests_with_coverage
on:
  push:
    branches:
      - master

jobs:
  unit-unit_tests_with_coverage:
    name: Unit test with coverage on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:

      # Checkout code and get packages.
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Readm FVM config
        uses: kuhnroyal/flutter-fvm-config-action@v1

      - name: Set up Flutter.
        uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}

      - run: flutter --version

      - name: Install Tools
        run: |
          ./tools/install_tools.sh

      - name: Bootstrap Workspace
        run: flutter pub global run melos bootstrap

      - name: Activate remove_from_coverage
        run: flutter pub global run melos run test:coverage:init

      - name: Run tests with coverage
        run: flutter pub global run melos run test::unit:coverage --no-select

      - name: Upload actual unit tests coverage codecov
        uses: codecov/codecov-action@v1
        with:
          files: packages/*/coverage/lcov.info
          flags: unit_tests
          fail_ci_if_error: true

      # Flutter don't include files in coverage which not touched with tests
      # so we need to add all files manually
      - name: Run coverage_helper_test.dart to get total coverage
        run: flutter pub global run melos run test:unit:coverage:helper --no-select

      - name: Upload coverage_helper_test.dart coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          files: packages/*/coverage/lcov.info
          flags: all_tests
          fail_ci_if_error: true