name: unit_tests_with_coverage
on:
  push:
    branches:
      - master

jobs:
  unit-test:
    name: Unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      # needed by flutter-action
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      # Set up Flutter.
      - name: Clone Flutter repository
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.3'
          channel: 'any'
        # fork version with fvm parsing
        # uses: xal/flutter-action@feature/read-version-from-file-fixes
        # with:
        # parse: 'fvm'

      - run: flutter --version

      # Checkout code and get packages.
      - name: Checkout repository
        uses: actions/checkout@v2

      - run: flutter pub get


      - name: Run Flutter unit tests
        run: flutter test --coverage --no-pub --no-null-assertions --no-track-widget-creation -j 10 --coverage-path=coverage/lcov_test.info


      - name: Upload to codecov
        uses: codecov/codecov-action@v1
        with:
          files:
            coverage/lcov_test.info
          flags: unit_tests
          fail_ci_if_error: true

      #       Flutter don't include files in coverage which not touched with tests
      #       so we need to add all files manually
      - name: Add missed classes to coverage report
        uses: stelynx/dart-full-coverage@v1.0.5
        with:
          package: fedi

      - name: Run Flutter unit tests
        run: flutter test/coverage_helper_test --coverage --no-pub --no-null-assertions --no-track-widget-creation -j 10 --coverage-path=coverage/lcov_all.info

      - name: Upload to codecov
        uses: codecov/codecov-action@v1
        with:
          files:
            coverage/lcov_all.info
          flags: all_tests
          fail_ci_if_error: true