name: unit_tests
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - master

jobs:
  unit-test:
    name: Unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      # needed by flutter-action
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      # Set up Flutter.
      - name: Clone Flutter repository
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.3'
          channel: 'any'
        # fork version with fvm parsing
        # uses: xal/flutter-action@feature/read-version-from-file-fixes
        # with:
        # parse: 'fvm'

      - run: flutter --version

      # Checkout code and get packages.
      - name: Checkout repository
        uses: actions/checkout@v2

      - run: flutter pub get

      - name: Run Flutter unit tests
        run: flutter test --no-pub --no-null-assertions --no-track-widget-creation --no-test-assets -j 10